In [12]:
import numpy as np 

n = 6
tridag = np.array([[2,3,0,0,0,0], [4,3,1,0,0,0], [0,2,5,4,0,0], [0,0,5,7,8,0],[0,0,0,1,5,2], [0,0,0,0,-2,5]])
a = np.array([4,2,5,1,-2])
b = np.array([2,3,4,7,5,5])
c = np.array([3,1,4,8,2])

tridag_work = tridag.copy()
print(tridag_work)


for i in range(1,n):
    tridag_work[i,:] = a[i-1]/b[i-1]*tridag_work[i-1,:]

tridag_work[-1,:] = tridag_work[-1,:]/tridag_work[-1,:]

for i in range(1,n):
    tridag_work[-1-i,:] = (tridag_work[-1-i,:] - tridag_work[-i,:]*tridag_work[-1-i,:])/tridag_work[-1-i,:]

print(tridag_work)


#hmm, something wrong.

[[ 2  3  0  0  0  0]
 [ 4  3  1  0  0  0]
 [ 0  2  5  4  0  0]
 [ 0  0  5  7  8  0]
 [ 0  0  0  1  5  2]
 [ 0  0  0  0 -2  5]]
[[                   0 -1229782938247303424 -9223372036854775808
  -9223372036854775808 -9223372036854775808 -9223372036854775808]
 [                   1  1229782938247303424 -9223372036854775808
  -9223372036854775808 -9223372036854775808 -9223372036854775808]
 [                   0  1844674407370955264 -9223372036854775808
  -9223372036854775808 -9223372036854775808 -9223372036854775808]
 [                   1 -1844674407370955264 -9223372036854775808
  -9223372036854775808 -9223372036854775808 -9223372036854775808]
 [-9223372036854775808 -9223372036854775808 -9223372036854775808
  -9223372036854775808 -9223372036854775808 -9223372036854775808]
 [-9223372036854775808 -9223372036854775808 -9223372036854775808
  -9223372036854775808 -9223372036854775808 -9223372036854775808]]


/tmp/ipykernel_8008/3551501493.py:16: RuntimeWarning: invalid value encountered in true_divide
  tridag_work[-1,:] = tridag_work[-1,:]/tridag_work[-1,:]
/tmp/ipykernel_8008/3551501493.py:19: RuntimeWarning: invalid value encountered in true_divide
  tridag_work[-1-i,:] = (tridag_work[-1-i,:] - tridag_work[-i,:]*tridag_work[-1-i,:])/tridag_work[-1-i,:]
